[versions]

# general
yui = "dev-3f0bdca"
lombok = "1.18.42"

# plugins
shadow = "9.3.0"

[libraries]

# general
yui = { group = "me.whereareiam", name = "Yui", version.ref = "yui" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }

[plugins]

shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[bundles]